name: Release firmware (PlatformIO)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build
        run: pio run   # oder: pio run -e m5stack_basic

      - name: Find firmware file
        id: fw
        shell: bash
        run: |
          set -e
          FILE=$(ls -1 .pio/build/*/firmware.bin | head -n1)
          echo "path=$FILE" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.fw.outputs.path }}
